<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQBe0V9c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQBe0V9c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQBe0V9c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQBe0V9c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQBe0V9c\App_KernelDevDebugContainer([
    'container.build_hash' => 'QBe0V9c',
    'container.build_id' => 'fba96e3d',
    'container.build_time' => 1706971324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQBe0V9c');
