<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVKgsnrs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVKgsnrs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVKgsnrs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVKgsnrs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVKgsnrs\App_KernelDevDebugContainer([
    'container.build_hash' => 'VKgsnrs',
    'container.build_id' => '59469f81',
    'container.build_time' => 1707405230,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVKgsnrs');
